#Tardis Mod 2 1.19 TOML

modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="MIT"

[[mods]] #mandatory

modId="peppermod" #mandatory
version="0.0.0.3" #mandatory
displayName="Tardis Pepper Mod" #mandatory
logoFile="BlueBox.png" #optional
credits="Mom and KD got me into this." #optional
authors="Dave does not do pretty" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
It worked before, maybe it will work again.
You should find a pepper in Creative mode, if you
search for 'pepper'.  It will also work as food.
'''

[[dependencies.peppermod]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.peppermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
